################################################################################
# Observations
################################################################################

[ns=Observations]
sort-key=sec-d
title=Observation options

################################################################
# Surface synoptic fields.
[ns=Observations/Synoptic]
sort-key=sec-d2
title=Synoptic observations

[template variables=SURFACE_SYNOP_OBS]
ns=Observations/Synoptic
description=Compare with surface synoptic observations
type=python_boolean
compulsory=true
sort-key=0synop1a
trigger=template variables=SURFACE_SYNOP_FIELDS: True;
        template variables=USE_WMO_STATION_NUMBERS: True;
        template variables=SURFACE_SYNOP_INTERVAL: True;
        template variables=SURFACE_SYNOP_OFFSET: True;
        template variables=SURFACE_SYNOP_DIFFS: True;

[template variables=SURFACE_SYNOP_FIELDS]
ns=Observations/Synoptic
title=Surface synoptic observations
description=Synoptic observations
help=Name of field in the style of the MetDB.
compulsory=true
type=python_list
sort-key=0synop1b

[template variables=SURFACE_SYNOP_DIFFS]
ns=Observations/Synoptic
description=Calculate the corresponding differences.
type=python_boolean
compulsory=true
sort-key=0synop1c
trigger=template variables=SURFACE_SYNOP_MODEL_FIELDS: True;

[template variables=SURFACE_SYNOP_MODEL_FIELDS]
ns=Observations/Synoptic
title=Corresponding model variables
description=Synoptic observations
help=Name of field in the model: the order must match that of the synoptic observations
compulsory=true
type=python_list
sort-key=0synop1d

[template variables=USE_WMO_STATION_NUMBERS]
ns=Observations/Synoptic
description=Use WMO numbers
help=Select to set stations by WMO station or block number.
compulsory=true
type=python_boolean
sort-key=0synop1e
trigger=template variables=WMO_BLOCK_STTN_NMBRS: True;

[template variables=WMO_BLOCK_STTN_NMBRS]
ns=Observations/Synoptic
title=WMO Block or station numbers.
description=WMO numbers
help=WMO block numbers (2 digits) or station numbers (5 digits).
compulsory=true
type=python_list
sort-key=0synop1f

[template variables=SURFACE_SYNOP_INTERVAL]
ns=Observations/Synoptic
title=Interval between synoptic observations
description=Synoptic observations
help=The time interval between retrievals of synoptic observations.
compulsory=true
type=quoted
sort-key=0synop1g

[template variables=SURFACE_SYNOP_OFFSET]
ns=Observations/Synoptic
title=Offset for synoptic observations
description=Offset for observations
help=The offset of the first retrieved observations relative to the initial time.
compulsory=true
type=quoted
sort-key=0synop1h

################################################################
# Cardington UK Research Observations
[Observations/Cardington]
ns=Observations/Cardington
sort-key=sec-d4
title=Cardington UK observations

# Air temperature timeseries
[template variables=CARDINGTON_AIR_TEMPERATURE_SINGLE_POINT_TIME_SERIES]
ns=Observations/Cardington
title=Cardington air temperature timeseries
description=Create Cardington diagnostic variable timeseries
type=python_boolean
compulsory=true
sort-key=0card1

# Relative humidity timeseries
[template variables=CARDINGTON_RELATIVE_HUMIDITY_SINGLE_POINT_TIME_SERIES]
ns=Observations/Cardington
title=Cardington relative humidity timeseries
description=Create Cardington diagnostic variable timeseries
type=python_boolean
compulsory=true
sort-key=0card2
