# See https://pre-commit.com for more information
---
ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        exclude: src/CSET/cset_workflow/app/metplus_point_stat/file/metoffice/PointStat_METplus_UKV.conf

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: aab412d509121cb5f7533134b7e67f9fab59c682  # frozen: v0.16.4
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a6564f5d57444e123433a5c9af733e3975c77229  # frozen: v0.11.0.1-1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: sort-json
        name: Sort JSON
        description: Recursively sort JSON files by key.
        entry: ./scripts/sort_json.py
        language: script
        types: [json]
        files: src/CSET/operators/_colorbar_definition.json

  - repo: local
    hooks:
      - id: regenerate-rose-meta
        name: Regenerate rose metadata
        description: Ensure the rose metadata has been generated from its template.
        entry: ./scripts/generate_rose_meta.py
        language: python
        files: src/CSET/cset_workflow/meta/
        additional_dependencies:
          - jinja2

  - repo: local
    hooks:
      - id: check-conda-lockfiles
        name: Check conda lockfiles are up-to-date
        description: Ensure the conda lockfiles include new dependencies.
        entry: ./scripts/check-conda-lockfiles.sh
        language: script
        files: requirements/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10240"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        # Prevent PP files being inappropriately "fixed".
        exclude: ^.+\.pp$
      - id: trailing-whitespace
