################################################################################
# Verification
################################################################################

[Verification]
ns=Verification
sort-key=sec-e
title=Verification

[template variables=RUN_METPLUS_POINT_STAT]
ns=Verification
description=Run METplus point stat in the workflow.
help=If True, it will enable the production of verification statistics against
    point observations (i.e. land-synop, sonde,...).
type=python_boolean
trigger=template variables=METPLUS_OPT_CONFIG_KEYS: True;
        template variables=METPLUS_OBS_DIR: True;
compulsory=true
sort-key=met1

[template variables=RUN_METPLUS_GRID_STAT]
ns=Verification
description=Run METplus grid stat in the workflow.
help=If True, it will enable the production of verification statistics against
    gridded data (i.e. radar, analysis,...).
type=python_boolean
trigger=template variables=METPLUS_OPT_CONFIG_KEYS: True;
        template variables=METPLUS_ANA_DIR: True;
compulsory=true
sort-key=met2

[template variables=METPLUS_OPT_CONFIG_KEYS]
ns=Verification
description=Which METplus configuration to run.
help=Selects the site/model specific configuration to use. The configuration must
    exist as restricted files in
    https://github.com/MetOffice/CSET-restricted-files/tree/main/app/{app_name}/file
type=quoted
value-hints="metoffice", "niwa", "nci-gadi"
sort-key=met3

[template variables=METPLUS_OBS_DIR]
ns=Verification
description=Path to directory containing observations in MET ASCII format.
type=quoted
sort-key=met4

[template variables=METPLUS_ANA_DIR]
ns=Verification
description=Path to directory containing analysis in MET netcdf format.
type=quoted
sort-key=met5


###################################
# Scores
[Verification/Scores]
ns=Verification/Scores
sort-key=scores
title=Scores

[template variables=SCORES_RMSE_SPATIAL]
ns=Verification/Scores
description=Create spatially mapped RMSE plots for the specified surface fields.
            The analysis method(s) set in SPATIAL_SURFACE_FIELD_METHOD will be used.
type=python_boolean
compulsory=true
sort-key=scores1

[template variables=SCORES_RMSE_TIMESERIES]
ns=Verification/Scores
description=Create a timeseries of the RMSE for the specified surface fields.
type=python_boolean
compulsory=true
sort-key=scores2

[template variables=SCORES_CRPS_FOR_ENSEMBLE]
ns=Verification/Scores
description=Create a timeseries of the CRPS for comparing ensemble members to control.
type=python_boolean
compulsory=true
trigger=template variables=METHOD_FOR_CRPS: True;
        template variables=CONTROL_MEMBER;
sort-key=scores3

[template variables=METHOD_FOR_CRPS]
ns=Verification/Scores
title=Method for CRPS
description=What method CRPS for ensembles should use
help=ecdf assumes empirical CDF
    fair gives an approximated CRPS assuming that the ensemble values can be interpreted as a random sample from an underlying predictive distribution
values="ecdf", "fair"
value-titles=ecdf, fair
compulsory=true
sort-key=scores3a

[template variables=CONTROL_MEMBER]
ns=Verification/Scores
title=Control member for CRPS calculation
description=What index the control member is in the realization coordinate
help=Usually this should be set to 0, but in some case it may be 1.
type=integer
compulsory=true
sort-key=scores3b
