################################################################################
# Verification
################################################################################

[Verification]
ns=Verification
sort-key=sec-e
title=Verification

[template variables=RUN_METPLUS_POINT_STAT]
ns=Verification
description=Run METplus point stat in the workflow.
help=If True, it will enable the production of verification statistics against
    point observations (i.e. land-synop, sonde,...).
type=python_boolean
trigger=template variables=METPLUS_OPT_CONFIG_KEYS: True;
        template variables=METPLUS_OBS_DIR: True;
compulsory=true
sort-key=met1

[template variables=RUN_METPLUS_GRID_STAT]
ns=Verification
description=Run METplus grid stat in the workflow.
help=If True, it will enable the production of verification statistics against
    gridded data (i.e. radar, analysis,...).
type=python_boolean
trigger=template variables=METPLUS_OPT_CONFIG_KEYS: True;
        template variables=METPLUS_ANA_DIR: True;
compulsory=true
sort-key=met2

[template variables=METPLUS_OPT_CONFIG_KEYS]
ns=Verification
description=Which METplus configuration to run.
help=Selects the site/model specific configuration to use. The configuration must
    exist as restricted files in
    https://github.com/MetOffice/CSET-restricted-files/tree/main/app/{app_name}/file
type=quoted
value-hints="metoffice", "niwa", "nci-gadi"
sort-key=met3

[template variables=METPLUS_OBS_DIR]
ns=Verification
description=Path to directory containing observations in MET ASCII format.
type=quoted
sort-key=met4

[template variables=METPLUS_ANA_DIR]
ns=Verification
description=Path to directory containing analysis in MET netcdf format.
type=quoted
sort-key=met5


###################################
# Scores
[Verification/Scores]
ns=Verification/Scores
sort-key=scores
title=Scores

[template variables=SPATIAL_SCORES_RMSE]
ns=Verification/Scores
description=Create spatially mapped RMSE plots for the specified surface fields.
            The analysis method(s) set in SPATIAL_SURFACE_FIELD_METHOD will be used.
type=python_boolean
compulsory=true
sort-key=scores1

[template variables=TIMESERIES_SCORES_RMSE]
ns=Verification/Scores
description=Create a timeseries of the RMSE for the specified surface fields.
type=python_boolean
compulsory=true
sort-key=scores2
