[command]
default=plot_stats.py --conf=${CONF_FILE} --outdir=${OUT_DIR} --start=${START_DATE} --end=${END_DATE} --expid=${EXPID}

[env]
CONDA_VENV_LOCATION=${CONDA_METPLUS_VENV_LOCATION}
CONF_FILE=pointstat_cnt.rc
OUT_DIR=${PLOT_DIR}
START=${START_DATE}
END=${END_DATE}
EXPID=UMTests_NIWA_obs

DB_DIR=${CYLC_WORKFLOW_SHARE_DIR}/verpy_dbs
TABLENAME=${STREAM}_${VER_METHOD}_table
DB_NAME=${VER_METHOD}_${STAT_TYPE}_${STAT_TYPE}.db
