[command]
# Read in files from ODB2 files by providing a strftime pattern
default = mkdir -p "$METPLUS_OBS_DIR"
        = app_env_wrapper prepODB2.py --valid-time "$OBS_TIMES" --output "$METPLUS_OBS_DIR/${CYLC_TASK_CYCLE_POINT}.ascii" $CUSTOM_ODB2_PATTERN
