[command]
# Read in files from ig2
default = mkdir -p "$METPLUS_OBS_DIR"
        = app_env_wrapper prepBureauNCI.py --system "$METPLUS_OBS_SYSTEM" --valid-time "$OBS_TIMES" --output "$METPLUS_OBS_DIR/obs.%Y%m%dT%H%MZ.ascii"
