[command]
# Read in files from ig2
default = mkdir -p "$METPLUS_OBS_DIR"
        = app_env_wrapper prepBomNCI.py --system "$METPLUS_OBS_SYSTEM" --valid-times "R${ANALYSIS_LENGTH}/${CYLC_TASK_CYCLE_POINT}/PT1H" --output "$METPLUS_OBS_DIR/${CYLC_TASK_CYCLE_POINT}.ascii"
