[command]
default = mkdir -p "$METPLUS_OBS_DIR"
        = app_env_wrapper prep-obs-nci-gadi.py --length "$ANALYSIS_LENGTH" --system "$METPLUS_OBS_SYSTEM" --output "$METPLUS_OBS_DIR/${CYLC_TASK_CYCLE_POINT}.ascii"
