blank_issues_enabled: false
contact_links:
  - name: CSET Community Support
    url: https://github.com/MetOffice/simulation-systems/discussions/categories/cset-toolkit
    about: Please ask and answer questions here.
