# Prepare obs data for metplus
# Data must be:
#   - In a format recognised by metplus
#     https://metplus.readthedocs.io/projects/met/en/latest/Users_Guide/reformat_point.html#ascii2nc-tool
#   - Include fields required by metplus analyses
# Data should be output to directory $METPLUS_OBS_DIR
# Sites can override this command in an opt file if they need to pre-process data

[command]
default = /bin/true
