# Perform verification against rain gauges from JIVE

[config]
POINT_STAT_MESSAGE_TYPE = ADPSFC
POINT_STAT_DESC = JIVE

OBS_POINT_STAT_INPUT_DIR = /g/data/dp9/verifiation/data/met/jive/precip
OBS_POINT_STAT_INPUT_TEMPLATE = JIVE_APCP_{ENV[METPLUS_PRECIP_ACCUMULATION]}_{valid?fmt=%Y0101-%Y1231}

FCST_POINT_STAT_VAR1_NAME = {ENV[METPLUS_PRECIP_VAR]}
FCST_POINT_STAT_VAR1_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S?shift={FCST_SHIFT}},*,*)"
FCST_POINT_STAT_VAR1_THRESH = >=0.2,>=1.0,>=4.0,>=8.0,>=12.0

OBS_POINT_STAT_VAR1_NAME = APCP
OBS_POINT_STAT_VAR1_LEVELS = {ENV[METPLUS_PRECIP_ACCUMULATION]}

OBS_POINT_STAT_WINDOW_BEGIN = -0
OBS_POINT_STAT_WINDOW_END = 0

POINT_STAT_OUTPUT_FLAG_CNT = BOTH