[config]
###
# POINT_STAT Settings
#https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#pointstat
###

MODEL = UM
POINT_STAT_DESC = surface

POINT_STAT_REGRID_TO_GRID = FCST
POINT_STAT_REGRID_METHOD = NEAREST
POINT_STAT_REGRID_WIDTH = 1
POINT_STAT_REGRID_VLD_THRESH = 0.5

POINT_STAT_MASK_GRID = FULL

POINT_STAT_FCST_FILE_TYPE = NETCDF_NCCF
POINT_STAT_MESSAGE_TYPE = "ADPSFC"

FCST_POINT_STAT_VAR1_NAME = air_temperature
FCST_POINT_STAT_VAR1_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S?shift={FCST_SHIFT}},*,*)"
FCST_POINT_STAT_VAR1_THRESH = <=273, >273

OBS_POINT_STAT_VAR1_NAME = t2m
OBS_POINT_STAT_VAR1_LEVELS = P0
OBS_POINT_STAT_VAR1_THRESH = <=273, >273

FCST_POINT_STAT_VAR2_NAME = relative_humidity
FCST_POINT_STAT_VAR2_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S?shift={FCST_SHIFT}},*,*)"
FCST_POINT_STAT_VAR2_THRESH =  <60, >95

OBS_POINT_STAT_VAR2_NAME = rh2m
OBS_POINT_STAT_VAR2_LEVELS = P0
OBS_POINT_STAT_VAR2_THRESH = <60, >95

OBS_POINT_STAT_WINDOW_BEGIN = -1800
OBS_POINT_STAT_WINDOW_END = 1800

POINT_STAT_OUTPUT_FLAG_CNT = BOTH
