[template variables]
SITE="nci-gadi"

# Storage flags to add
NCI_STORAGE=["gdata/dp9"]

# Where to store output website (view from ARE virtual desktop)
WEB_DIR="~/public_html/$CYLC_WORKFLOW_NAME"

# Default module
CSET_ENV_USE_MODULES = True
CSET_ENV_SEPARATE_MET = False
MODULES_PURGE = ""
MODULES_LIST = "/g/data/access/ngm/modules/cset/26.4.0"

# # Paths to local checkouts of repositories
# VERPY_DIR = "/path/to/verpy"
# CSET_DIR = "/path/to/cset"

# # Metplus information
# # OBS_SYSTEM can be access_g{3,4}, access_c{3,4}_{ad,bn,dn,nq,ph,sy,vt} or custom
# METPLUS_OBS_SYSTEM = "access_g4"
#
# # If OBS_SYSTEM is custom, what path should be read
# CUSTOM_ODB_PATTERN = "/path/to/files/%Y%m%dT%H%MZ.odb2"
