[command]
default=#app_env_wrapper run_metplus.py nci/pointstat.conf nci/surface.conf
precip=app_env_wrapper run_metplus.py nci/pointstat.conf nci/precip_jive.conf

# Don't inherit rose environment
[!env]
