[DEFAULT]

debug = false
#source = --- METplus output location, passed as parameter from app ---
#appdir = --- VerPy database location, passed as parameter from app ---

# Name for output table
# If not set, a csv file is produced instead
# output_table = --- passed as parameter from app ---
# Optional prefix for database file, defaults to ""
# db_prefix = --- passed as parameter from app ---

# Maximum leadtime in SBV table, defaults to 240
max_fcrs = 240
# Required leadtimes in SBV table, max_fcrs is ignored if this is set
#fcrs = -36, -12, 12, 36, 60, 84, 108, 132

# Elements used to pattern match files
# MET output types as a comma separated list
stat_type = cnt
# File prefix, often the name of the MET tool, defaults to ""
stream = point_stat
# Optional grid filter, defaults to ""
#grid = G000
# Optional date filter, defaults to ""
#vt = 20230101

# Use OBS_VALID_BEG instead of FCST_VALID_BEG, defaults to False
use_obs_vt = false
# Use FCST_VAR instead of OBS_VAR, defaults to False
use_fcst_var = false
# Use FCST_LEV instead of OBS_LEV, defaults to False
use_fcst_lev = false

# Recompute leadtimes from OBS_VALID_BEG and FCST_VALID_BEG, defaults to False
per_fc = false

# Max number of concurrent processes, defaults to 4
nproc = 4
