mode = rose_bunch

[bunch]
command-format=app_env_wrapper bake.sh %(recipe_file)s
# names=bake_%(recipe_file)s
# Can pool-size be changed when retrying a task?
pool-size=32

[bunch-args]
# How do I make this work?
# recipe_file=$($RECIPE_DIR/*.yaml)

# Where RECIPE_DIR for non DO_CASE_AGGREGATION is:
# RECIPE_DIR=$CYLC_WORKFLOW_SHARE_DIR/cycle/$CYLC_TASK_CYCLE_POINT/recipes
# And for DO_CASE_AGGREGATION is:
# RECIPE_DIR=$CYLC_WORKFLOW_SHARE_DIR/cycle/$CYLC_TASK_CYCLE_POINT/aggregation_recipes
