# Prepare forecast data for metplus
# Data must be:
#  - In netcdf format
#  - Include fields required by metplus analyses
#  - On a regular grid (set a subarea if model has variable resolution)
# Data should be output to directory $METPLUS_FCST_DIR

[command]
default = app_env_wrapper cset bake \
        =    --recipe prep_fcst.yaml \
        =    --output-dir "$METPLUS_FCST_DIR" \
        =    --MODEL_NAME "$MODEL_NAME" \
        =    --INPUT_PATHS "$INPUT_PATHS" \
        =    --VARNAME "$VARNAME" \
        =    --SUBAREA_TYPE "$SUBAREA_TYPE" \
        =    --SUBAREA_EXTENT "$SUBAREA_EXTENT" \
        =    --FILENAME "${MODEL_ID}.nc"

[env]
VARNAME = "['air_temperature','relative_humidity']"
