[config]

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

ASCII2NC_INPUT_DIR = {INPUT_BASE}
ASCII2NC_INPUT_TEMPLATE = {valid?fmt=%Y%m%d}T??00Z/surface/aircraftsondesurface.odb.tsv

ASCII2NC_OUTPUT_DIR = {OUTPUT_BASE}/obs_nc
ASCII2NC_OUTPUT_TEMPLATE = surface_{valid?fmt=%Y%m%d}.nc
