name = "Extract Instant Air Temperature"
description = """
Extracts out the instantaneous 1.5m air temperature from a file and writes it
to a new one.
"""

[[steps]]
  operator = "read.read_cubes"
  [steps.args]
    [steps.args.constraint]
      operator = "generate_constraints.generate_stash_constraints"
      input = "m01s03i236"

[[steps]]
  operator = "filters.filter_cubes"
  [steps.args]
    cell_methods = []
    [steps.args.stash]
      operator = "generate_constraints.generate_stash_constraints"
      input = "m01s03i236"

[[steps]]
  operator = "write.write_cube_to_nc"
  [steps.args]
    # This is a magic value that becomes the runtime output file path.
    file_path = "MAGIC_OUTPUT_PATH"
