[command]
default = /bin/true
precip = app_env_wrapper run_metplus nci-gadi/gridstat.conf nci-gadi/precip.conf nci-gadi/gpm.conf
       = app_env_wrapper run_metplus nci-gadi/gridstat.conf nci-gadi/precip.conf nci-gadi/rainfields.conf
