[config]

OBTYPE = GPM

# Daily files contain times 0015 to 2345
# Make sure valid time 0000 uses the previous day's file by adding a shift of -1s to valid times
OBS_GRID_STAT_INPUT_DIR = /g/data/dp9/da/verification/satellite/products/gpm/netcdf/imerg/NRTlate
OBS_GRID_STAT_INPUT_TEMPLATE = {valid?fmt=%Y}/gpm_imerg_NRTlate_V07B_{valid?fmt=%Y%m%d?shift=-1}.nc

OBS_VAR1_NAME = precipitation_flux
FCST_VAR1_NAME = stratiform_rainfall_flux
BOTH_VAR1_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S},*,*)"
