[config]
# GPM Satellite precipitation

OBTYPE = GPM

OBS_VAR1_NAME = precipitation_flux

# PcpCombine OBS
#
OBS_PCP_COMBINE_RUN = True
OBS_PCP_COMBINE_METHOD = ADD

OBS_PCP_COMBINE_INPUT_DIR = /g/data/dp9/da/verification/satellite/products/gpm/netcdf/imerg/NRTlate
OBS_PCP_COMBINE_INPUT_TEMPLATE = {valid?fmt=%Y?shift=-1800}/gpm_imerg_NRTlate_V???_{valid?fmt=%Y%m%d?shift=-1800}.nc
OBS_PCP_COMBINE_INPUT_NAMES = {OBS_VAR1_NAME}
OBS_PCP_COMBINE_INPUT_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S},*,*)"
OBS_PCP_COMBINE_INPUT_ACCUMS = 1H

OBS_PCP_COMBINE_OUTPUT_DIR = {OUTPUT_BASE}
OBS_PCP_COMBINE_OUTPUT_TEMPLATE = {OBTYPE}.{valid?fmt=%Y%m%d_%H%M}_A{VERIFY_ACCUM_H}.nc
OBS_PCP_COMBINE_OUTPUT_NAME = {OBS_VAR1_NAME}
OBS_PCP_COMBINE_OUTPUT_ACCUM = {VERIFY_ACCUM_H}H

# GridStat
#
OBS_GRID_STAT_INPUT_DIR = {OBS_PCP_COMBINE_OUTPUT_DIR}
OBS_GRID_STAT_INPUT_TEMPLATE = {OBS_PCP_COMBINE_OUTPUT_TEMPLATE}
OBS_GRID_STAT_VAR1_LEVELS = A{VERIFY_ACCUM_H}
OBS_GRID_STAT_VAR1_OPTIONS = is_precipitation = TRUE; set_attr_level = "A{VERIFY_ACCUM_H}";set_attr_units = "mm";
