[config]
# Sets up defaults for GridStat, specific obs types can override these

LOG_DIR = {ENV[CYLC_TASK_LOG_DIR]}
OUTPUT_BASE = {ENV[CYLC_TASK_WORK_DIR]}

MODEL = {ENV[MODEL_NAME]}
GRID_STAT_DESC = vs{OBTYPE}

PROCESS_LIST = GridStat

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%dT%H
INIT_BEG = {ENV[TASK_START_TIME]}
INIT_END = {ENV[TASK_START_TIME]}
INIT_INCREMENT = 1H
LEAD_SEQ = begin_end_incr(0,{ENV[FORECAST_LENGTH]},1)

FCST_GRID_STAT_INPUT_DIR = {ENV[METPLUS_FCST_DIR]}
FCST_GRID_STAT_INPUT_TEMPLATE = {ENV[MODEL_ID]}.nc

GRID_STAT_REGRID_TO_GRID = OBS
GRID_STAT_REGRID_METHOD = BILIN
GRID_STAT_REGRID_WIDTH = 2

GRID_STAT_OUTPUT_DIR =  {ENV[CYLC_TASK_SHARE_CYCLE_DIR]}
GRID_STAT_OUTPUT_TEMPLATE = Grid_Stat_{ENV[MODEL_NAME]}
GRID_STAT_OUTPUT_PREFIX = {OBTYPE}
