# Common METplus grid_stat configuration to make it work with CSET

[dir]
MET_INSTALL_DIR = {ENV[CONDA_PREFIX]}

[config]
PROCESS_LIST = GridStat

OUTPUT_BASE = {ENV[CYLC_TASK_SHARE_CYCLE_DIR]}
LOG_DIR = {ENV[CYLC_TASK_LOG_DIR]}

MODEL = {ENV[MODEL_NAME]}

# [!] Set this for your site/obs type in a site file
# OBTYPE =

###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = INIT

INIT_TIME_FMT = %Y%m%dT%H%MZ
INIT_BEG = {ENV[CYLC_TASK_CYCLE_POINT]}
INIT_END = {ENV[CYLC_TASK_CYCLE_POINT]}
INIT_INCREMENT = 1H

LEAD_SEQ = {ENV[LEAD_SEQ]}

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

FCST_GRID_STAT_INPUT_DIR = {ENV[CYLC_WORKFLOW_SHARE_DIR]}/cycle/{init?fmt=%Y%m%dT%H%MZ}/metplus_fcst
FCST_GRID_STAT_INPUT_TEMPLATE = {ENV[MODEL_ID]}.nc

# [!] Set this for your site/obs type in a site file
# OBS_GRID_STAT_INPUT_DIR =
# OBS_GRID_STAT_INPUT_TEMPLATE =

GRID_STAT_OUTPUT_DIR = {OUTPUT_BASE}
GRID_STAT_OUTPUT_TEMPLATE = grid_stat/{MODEL}/{OBTYPE}
GRID_STAT_OUTPUT_PREFIX = {MODEL}_vs_{OBTYPE}_{CURRENT_OBS_NAME}

# Default regridding
GRID_STAT_REGRID_TO_GRID = FCST
GRID_STAT_REGRID_METHOD = BILIN
GRID_STAT_REGRID_WIDTH = 2
