[config]
# Common settings for all precip observations, the specific observation file can override
PROCESS_LIST = PcpCombine, GridStat

FCST_ACCUM_H = {ENV[METPLUS_PRECIP_FCST_ACCUM_H]}
VERIFY_ACCUM_H = {ENV[METPLUS_PRECIP_VERIFY_ACCUM_H]}
VERIFY_ACCUM_H = 3

LEAD_SEQ = begin_end_incr(6, {ENV[FORECAST_LENGTH]}, {VERIFY_ACCUM_H})

FCST_VAR1_NAME = {ENV[METPLUS_PRECIP_FCST_VARIABLE]}

# PcpCombine FCST
#
PCP_COMBINE_SKIP_IF_OUTPUT_EXISTS = True

FCST_PCP_COMBINE_RUN = True
FCST_PCP_COMBINE_METHOD = ADD

FCST_PCP_COMBINE_INPUT_DIR = {ENV[METPLUS_FCST_DIR]}
FCST_PCP_COMBINE_INPUT_TEMPLATE = {ENV[MODEL_ID]}_precip.nc
FCST_PCP_COMBINE_INPUT_NAMES = {FCST_VAR1_NAME}
FCST_PCP_COMBINE_INPUT_LEVELS = "({valid?fmt=%Y%m%d_%H%M%S},*,*)"
FCST_PCP_COMBINE_INPUT_ACCUMS = {FCST_ACCUM_H}H

FCST_PCP_COMBINE_OUTPUT_DIR = {OUTPUT_BASE}
FCST_PCP_COMBINE_OUTPUT_TEMPLATE = {ENV[MODEL_ID]}.{init?fmt=%Y%m%d_%H%M}_L{lead?fmt=%HHH}_A{VERIFY_ACCUM_H}.nc
FCST_PCP_COMBINE_OUTPUT_NAME = {FCST_VAR1_NAME}
FCST_PCP_COMBINE_OUTPUT_ACCUM = {VERIFY_ACCUM_H}H

# GridStat
#
FCST_GRID_STAT_INPUT_DIR = {FCST_PCP_COMBINE_OUTPUT_DIR}
FCST_GRID_STAT_INPUT_TEMPLATE = {FCST_PCP_COMBINE_OUTPUT_TEMPLATE}
FCST_GRID_STAT_VAR1_LEVELS = "(*,*)"
FCST_VAR1_OPTIONS = is_precipitation = TRUE; set_attr_level = "A{VERIFY_ACCUM_H}";

BOTH_GRID_STAT_VAR1_THRESH = >=0.2,>=1.0,>=4.0,>=8.0,>=12.0

GRID_STAT_NEIGHBORHOOD_WIDTH = 1
GRID_STAT_NEIGHBORHOOD_SHAPE = SQUARE
GRID_STAT_NEIGHBORHOOD_COV_THRESH = >=0.5

GRID_STAT_OUTPUT_FLAG_CNT = BOTH
