name: Documentation

on:
  push:
    branches:
      - "main"
  # Run weekly so there is always built documentation available.
  schedule:
    - cron: "56 3 * * 1"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python -m pip install tox

      - name: Build documentation
        run: tox -e py310-linux-docs

      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/
          retention-days: 10
          if-no-files-found: error
