name: Documentation

on:
  push:
    branches:
      - "main"
  # Run weekly so there is always built documentation available.
  schedule:
    - cron: "56 3 * * 1"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Build docs with tox
        run: |
          tox -e docs --skip-missing-interpreters false
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/
          retention-days: 10
          if-no-files-found: error
