name: Weekly Checks

on:
  schedule:
    - cron: "8 4 * * 1"
  workflow_dispatch:

# Minimise default GITHUB_TOKEN permissions.
permissions: {}

defaults:
  run:
    # Use a login shell to pickup conda/micromamba initialisation.
    shell: bash -leo pipefail {0}

jobs:
  check-documentation-hyperlinks:
    if: "github.repository == 'MetOffice/CSET'"  # Skip on forks.
    name: Check documentation hyperlinks
    runs-on: ubuntu-latest
    # Give plenty of time as link checking third-party sites might be slow.
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
        with:
          environment-name: cset-dev
          environment-file: requirements/locks/latest
          cache-environment: true

      - name: Install local package
        run: pip install --no-deps .

      - name: Build documentation with Sphinx
        run: sphinx-build -b html --color "docs/source" "docs/build/html"

      - name: Check for broken hyperlinks
        run: sphinx-build -b linkcheck --color -W --keep-going "docs/source" "docs/build/linkcheck"

  full-tests:
    if: "github.repository == 'MetOffice/CSET'"  # Skip on forks.
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        py-ver: ["py312", "py313", "py314"]
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Setup conda environment
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
        with:
          environment-name: cset-dev
          environment-file: requirements/locks/${{ matrix.py-ver }}-lock-linux-64.txt
          cache-environment: true

      - name: Cache downloaded cartopy shapefiles
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          key: cartopy-shapefiles
          path: ~/.local/share/cartopy

      - name: Install local package
        run: pip install --no-deps .

      - name: Run full test suite
        env:
          PY_COLORS: "1"
        run: make test-full
