name = "Extract Instant Air Temperature"
description = """
This is a longer description. It should detail what the task takes in and
outputs.
"""

[[steps]]
  operator = "generate_constraints.generate_stash_constraints"

[[steps]]
  operator = "read.read_cubes"

[[steps]]
  operator = "filters.filter_cubes"
  [steps.extra_args]
    cell_methods = []
    [steps.extra_args.stash]
      operator = "generate_constraints.generate_stash_constraints"
      input = "stash"

[[steps]]
  operator = "write.write_cube_to_nc"
