name = "Extract Instant Air Temperature"
description = """
This is a longer description. It should detail what the task takes in and
outputs.
"""

[[steps]]
  operator = "operators.read.read_cubes"
  [steps.args]
    [steps.args.stash]
      operator = "operators.generate_constraints.generate_stash_constraints"
      input = "m01s03i236"

[[steps]]
  operator = "operators.filters.filter_cubes"
  [steps.args]
    cell_methods = []
    [steps.args.stash]
      operator = "operators.generate_constraints.generate_stash_constraints"
      input = "m01s03i236"

[[steps]]
  operator = "operators.write.write_cube_to_nc"
  [steps.args]
    # This is a magic key+value becomes the output file path.
    output_file_path = "output_file_path"
