[dir]
FCST_BASE = {ENV[METPLUS_FCST_DIR]}
OUTPUT_BASE = {ENV[CYLC_TASK_WORK_DIR]}
MET_INSTALL_DIR = {ENV[MET_INSTALL_DIR]}
START_TIME = {ENV[START_TIME]}
FORECAST_LENGTH = {ENV[FORECAST_LENGTH]}

[config]

######
# This is a sample configuration file which can be used as start point for local configurations
#####

# Documentation for this use case can be found at
# https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/ASCII2NC/ASCII2NC_python_embedding.html

# For additional information, please see the METplus Users Guide.
# https://metplus.readthedocs.io/en/latest/Users_Guide

###
# Processes to run
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#process-list
###

SCRUB_STAGING_DIR = False
PROCESS_LIST = EnsembleStat
LOG_ENSEMBLE_STAT_VERBOSITY = 4

###
# Time Info
# LOOP_BY options are INIT, VALID, RETRO, and REALTIME
# If set to INIT or RETRO:
#   INIT_TIME_FMT, INIT_BEG, INIT_END, and INIT_INCREMENT must also be set
# If set to VALID or REALTIME:
#   VALID_TIME_FMT, VALID_BEG, VALID_END, and VALID_INCREMENT must also be set
# LEAD_SEQ is the list of forecast leads to process
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#timing-control
###

LOOP_BY = INIT
INIT_TIME_FMT = %Y%m%dT%H
INIT_BEG = {START_TIME}
INIT_END = {START_TIME}
INIT_INCREMENT = 1H

#LEAD_SEQ = 0
LEAD_SEQ = begin_end_incr(0,{FORECAST_LENGTH},1)

###
# File I/O
# https://metplus.readthedocs.io/en/latest/Users_Guide/systemconfiguration.html#directory-and-filename-template-info
###

FCST_ENSEMBLE_STAT_INPUT_DIR = {FCST_BASE}/{START_TIME}/nc
FCST_ENSEMBLE_STAT_INPUT_TEMPLATE = met_{START_TIME}_utc_nzens_*.nc #Replace with Forecast file

OBS_ENSEMBLE_STAT_POINT_INPUT_DIR = {ENV[CYLC_WORKFLOW_SHARE_DIR]}/obs_nc
OBS_ENSEMBLE_STAT_POINT_INPUT_TEMPLATE = ascii2nc_{valid?fmt=%Y%m%d}T{valid?fmt=%2H}00.nc #Replace with Obs file

ENSEMBLE_STAT_OUTPUT_DIR =  {ENV[CYLC_TASK_SHARE_CYCLE_DIR]}
ENSEMBLE_STAT_OUTPUT_TEMPLATE = Ensemble_Stat_{ENV[MODEL_NAME]}

###
# ENSEMBLE_STAT Settings
#https://metplus.readthedocs.io/en/latest/Users_Guide/wrappers.html#ensemblestat
###

MODEL = NZENS

ENSEMBLE_STAT_REGRID_TO_GRID = FCST
ENSEMBLE_STAT_REGRID_METHOD = NEAREST
ENSEMBLE_STAT_REGRID_WIDTH = 1
ENSEMBLE_STAT_REGRID_VLD_THRESH = 0.5

ENSEMBLE_STAT_MASK_GRID = FULL

ENSEMBLE_STAT_FCST_FILE_TYPE = NETCDF_NCCF
ENSEMBLE_STAT_MESSAGE_TYPE = "ADPSFC"

FCST_ENSEMBLE_STAT_VAR1_NAME = air_temperature
FCST_ENSEMBLE_STAT_VAR1_LEVELS = "({lead?fmt=%H},*,*)"
FCST_ENSEMBLE_STAT_VAR1_THRESH = <=273, >273

OBS_ENSEMBLE_STAT_VAR1_NAME = TMP
OBS_ENSEMBLE_STAT_VAR1_LEVELS = Z0
OBS_ENSEMBLE_STAT_VAR1_THRESH = <=273, >273

FCST_ENSEMBLE_STAT_VAR2_NAME = relative_humidity
FCST_ENSEMBLE_STAT_VAR2_LEVELS = "({lead?fmt=%H},*,*)"
FCST_ENSEMBLE_STAT_VAR2_THRESH =  <60, >95

OBS_ENSEMBLE_STAT_VAR2_NAME = RH
OBS_ENSEMBLE_STAT_VAR2_LEVELS = Z0
OBS_ENSEMBLE_STAT_VAR2_THRESH = <60, >95

OBS_ENSEMBLE_STAT_WINDOW_BEGIN = -1800
OBS_ENSEMBLE_STAT_WINDOW_END = 1800

ENSEMBLE_STAT_PROB_CAT_THRESH = [ >273 ] #Needs to be VER specific
ENSEMBLE_STAT_PROB_PCT_THRESH = [ ==0.1 ]


ENSEMBLE_STAT_OUTPUT_FLAG_ECNT = BOTH
ENSEMBLE_STAT_OUTPUT_FLAG_RPS = BOTH
ENSEMBLE_STAT_OUTPUT_FLAG_RHIST = BOTH
ENSEMBLE_STAT_OUTPUT_FLAG_PCT = BOTH
